 #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031" 
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"
  
  
### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social: 
  
  - name: "Google+"
    tag: "google-plus"
    url: "plus.google.com/+SejoRuiz"
    protocol: "https://"

  
  - name: "LinkedIn"
    tag: linkedin
    url: es.linkedin.com/in/sergioruizpena/
    protocol: https://

  
  - name: GitHub
    tag: github
    url: github.com/sejoruiz
    protocol: https://

  
  - name: E-mail
    tag: envelope 
    url: sejoruiz@gmail.com
    protocol: "mailto:"

# Since I haven't been able to access social as a dict of dicts, we will use magic numbers to address each field. Dirty but no headaches
google_plus_index: 0
linkedin_index: 1
github_index: 2
email_index: 3

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines: 
    - Möllevångsgatan 24B, lgh 1302.
    - 21 420, Malmö,
    - Sweden.
tel: +46-(0)79-334-6454
email: sejoruiz@gmail.com

### GENERAL DATA FOR VARIOUS LOCATIONS ###
    
# Members information. Shown on About page.
    
# Clients information. Shown on Home and About pages.
ext_resources:
  - name: Jekyll
    img: jekyll.png
    url: http://www.jekyllrb.com
  - name: Raspberry
    img: raspberry.png
    url: http://www.raspberrypi.org
  - name: GitHub
    img: github.png
    url: http://www.github.com
  - name: ArchLinux
    img: arch.png
    url: http://www.archlinux.org
# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "This website was created by Sergio Ruiz. Any feed back is welcomed. You can find my contact info in Contact. Thank you for your visit!"

# Testimonial content. Shown on Home and About page. 
testimonial:
    message: "I am a master in telecommunication engineer currently working as network software developer. I've got lots of projects in my head that I will be posting in this website. I was born in Spain, but I'm currently living in Malmö, Sweden. You can contact me in English or Spanish. I'm working on my Swedish, but it's not so good yet. So, anyway, I hope you enjoy your time here. Cheers!"
    author: Sergio Ruiz
    position: Network Software Developer