### GENERAL SETTINGS ###

# Site settings
title: Sergio Ruiz's website.
description: "Sergio Ruiz's personal website. Telecommunications engineer in love with technology."
baseurl: "" #important: start with /
url: "http://sergioruiz.duckdns.org"
project_img: "/assets/img/project/"
# Build settings
markdown: rdiscount
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031" 
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"
  
  
### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: google-plus
    url: https://plus.google.com/+SejoRuiz
  - title: linkedin
    url: es.linkedin.com/in/sergioruizpena/
  - title: github
    url: https://github.com/sejorules    
  - title: envelope 
    url: mailto:sejoruiz@gmail.com
# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines: 
    - Gunnilbogatan 2, lgh 1106.
    - 723 40, Västeras,
    - Sweden.
email: sejoruiz@gmail.com
tel: +46-72-0499-528


### GENERAL DATA FOR VARIOUS LOCATIONS ###
    
# Members information. Shown on About page.
    
# Clients information. Shown on Home and About pages.
ext_resources:
  - name: dribbble
    img: client01.png
  - name: Code is Poetry
    img: client02.png
  - name: Vimeo
    img: client03.png
  - name: VimeoPro
    img: client04.png
    
# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "I am a telecommunication engineer (Master level) with lots of projects in my head. I was born in Spain, but I'm currently living in Sweden, in Västeras. I have always shown interest about the technology, so it's very exciting to run this website with some of my current work. I hope I can share as many projects as possible. Oh, and if you like any project, you can always grab the code from GitHub. You can also contact me if you have any suggestion, question, or any other reason."

# Testimonial content. Shown on Home and About page. 
testimonial:
    message: "With this website, you can check and interact every project I have worked on, and even fork it to try! I really hope you like it, and you are very welcomed to contact me!"
    author: Sergio Ruiz
    position: Telecommunication Engineer (Master level)
