### GENERAL SETTINGS ###

# Site settings
title: Sergio Ruiz's website.
description: "Sergio Ruiz personal website"
baseurl: "" #important: start with /
url: "http://sejoruiz.github.io"
project_img: "/assets/img/project/"
# Build settings
markdown: kramdown 
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031" 
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"
  
  
### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: google-plus
    url: https://plus.google.com/+SejoRuiz
  - title: linkedin
    url: https://es.linkedin.com/in/sergioruizpena/
  - title: github
    url: https://github.com/sejoruiz   
  - title: envelope 
    url: mailto:sejoruiz@gmail.com
# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines: 
    - Gunnilbogatan 2, lgh 1106.
    - 723 40, Västeras,
    - Sweden.
email: sejoruiz@gmail.com
tel: +46-072-0499-528
github: https://github.com/sejoruiz
linkedin: https://es.linkedin.com/in/sergioruizpena/
googleplus: https://plus.google.com/+SejoRuiz
### GENERAL DATA FOR VARIOUS LOCATIONS ###
    
# Members information. Shown on About page.
    
# Clients information. Shown on Home and About pages.
ext_resources:
  - name: Jekyll
    img: jekyll.png
    url: http://www.jekyllrb.com
  - name: Raspberry
    img: raspberry.png
    url: http://www.raspberrypi.org
  - name: GitHub
    img: github.png
    url: http://www.github.com
  - name: ArchLinux
    img: arch.png
    url: http://www.archlinux.org
# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "This webpage was created by Sergio Ruiz. If you have any suggestion, or want to report a bug, please head to Contact. Thank you for your visit!"

# Testimonial content. Shown on Home and About page. 
testimonial:
    message: "I am a telecommunication engineer (Master level) with lots of projects in my head. I was born in Spain, but I'm currently living in Västeras, Sweden. Since I was a kid and was disassembling computers for fun, I have felt technology was my thing. I find exciting to run this website with some of my current work. I hope I can share as many projects as possible."
    author: Sergio Ruiz
    position: Network Software Engineer
